version: 2.1
orbs:
  node: circleci/node@7.2.1
jobs:
  test:
    docker:
      - image: cimg/node:24.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
workflows:
  test-on-push:
    jobs:
      - test
